---
Resources:
  BucketsS3:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "financeiro-cayoesn"
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
